version: "3.9"
services:
  angular:
    build: ./frontend
    container_name: angular-app
    ports:
      - "80:80"
    depends_on:
      - springboot

  springboot:
    build: ./backend
    container_name: springboot-app
    expose:
      - "8080"
